version: '3.8'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  dockerapi:
    container_name: dockerapi
    image: dockerapi:latest
    depends_on:
      - postgres_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=blogdb;username=bloguser;password=bloguser"
      ASPNETCORE_HTTP_PORTS: "80"
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - dockerapi-dev  
  
  postgres_image:
    container_name: postgres_image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "bloguser"
      POSTGRES_DB: "blogdb"
    networks:
      - dockerapi-dev
volumes:
  db_volume:
         
    
     